-- The database under ./db is autogenerated. Changing the entries there
-- will result in a data loss whenever a new database gets extracted.
-- To be able to customize and/or fix entries that aren't yet detected
-- by the extractor logic, this file here can be used to save overwrites.
--
-- This pack is the TurtleWoW database with the Octo pack folded in, so this
-- file carries three things in order:
--   1. records the Octo DB has that the TurtleWoW build does not
--   2. the Octo pack's own corrections
--   3. the TurtleWoW pack's own corrections
-- Records come first so that anything indexing into them further down finds
-- them present.

do -- Octo-only records, carried over from the pfQuest-octo database
  -- 24 entries where the Octo DB holds real data the Kludge Bureau turtle build
  -- does not: either it has no entry for that id, or only a "_" placeholder.
  -- Kept here rather than patched into the autogenerated files under ./db, so a
  -- future database refresh cannot silently drop them.
  -- quests: 1 absent from the turtle build, 0 only a placeholder there
  pfDB["quests"]["data-turtle"][1704] = {
      ["class"] = 1,
      ["end"] = {
        ["U"] = { 6169 },
      },
      ["lvl"] = 28,
      ["min"] = 20,
      ["pre"] = { 1701 },
      ["race"] = 589,
      ["start"] = {
        ["U"] = { 5413 },
      },
    }

  -- units: 6 absent from the turtle build, 0 only a placeholder there
  pfDB["units"]["data-turtle"][5327] = {
      ["coords"] = {
        [1] = { 28.1, 59.4, 357, 300 },
        [2] = { 26, 59.2, 357, 300 },
        [3] = { 34, 56.3, 357, 300 },
        [4] = { 35.4, 52.2, 357, 300 },
        [5] = { 35.9, 51.6, 357, 300 },
        [6] = { 37.2, 50, 357, 300 },
        [7] = { 36, 48.6, 357, 300 },
        [8] = { 39.6, 48.4, 357, 300 },
        [9] = { 37.9, 45.8, 357, 300 },
        [10] = { 39.7, 45.2, 357, 300 },
        [11] = { 36.8, 44.1, 357, 300 },
        [12] = { 37.7, 42.2, 357, 300 },
        [13] = { 36.8, 41.9, 357, 300 },
        [14] = { 33.2, 32.1, 357, 300 },
      },
      ["lvl"] = "44-45",
      ["rnk"] = "1",
    }
  pfDB["units"]["data-turtle"][7044] = {
      ["coords"] = {
        [1] = { 89.9, 43.9, 46, 500 },
        [2] = { 91.5, 37.7, 46, 500 },
        [3] = { 84.9, 28.5, 46, 500 },
      },
      ["lvl"] = "50-52",
      ["rnk"] = "1",
    }
  pfDB["units"]["data-turtle"][11661] = {
      ["coords"] = {
        [1] = { 32.3, 48.9, 2717, 7200 },
        [2] = { 32.5, 47.1, 2717, 7200 },
      },
      ["lvl"] = "62",
      ["rnk"] = "1",
    }
  pfDB["units"]["data-turtle"][12259] = {
      ["coords"] = {
        [1] = { 32.8, 48, 2717, 604800 },
      },
      ["lvl"] = "63",
      ["rnk"] = "3",
    }
  pfDB["units"]["data-turtle"][12360] = {
      ["coords"] = {
        [1] = { 31, 62.1, 141, 120 },
        [2] = { 25.4, 50, 141, 300 },
        [3] = { 66.5, 73, 1657, 120 },
        [4] = { 39.4, 14.9, 1657, 300 },
      },
      ["fac"] = "AH",
      ["lvl"] = "1-2",
    }
  pfDB["units"]["data-turtle"][62229] = {
      ["coords"] = {},
      ["lvl"] = "34-35",
    }

  -- objects: 5 absent from the turtle build, 0 only a placeholder there
  pfDB["objects"]["data-turtle"][944] = {
      ["coords"] = {
        [1] = { 39.1, 91.4, 139, 25 },
      },
      ["fac"] = "AH",
    }
  pfDB["objects"]["data-turtle"][21145] = {
      ["coords"] = {
        [1] = { 30.7, 62.8, 141, 300 },
        [2] = { 64.7, 76.3, 1657, 300 },
      },
    }
  pfDB["objects"]["data-turtle"][181021] = {
      ["coords"] = {
        [1] = { 54.1, 34.6, 1, 120 },
        [2] = { 45.5, 12.1, 14, 120 },
        [3] = { 46.4, 9.2, 14, 120 },
        [4] = { 30.9, 57.1, 141, 120 },
        [5] = { 31.2, 57.1, 141, 120 },
        [6] = { 31.6, 57.1, 141, 120 },
        [7] = { 36.1, 54.4, 141, 120 },
        [8] = { 35.2, 54.4, 141, 120 },
        [9] = { 30.9, 53.6, 141, 120 },
        [10] = { 31.2, 53.5, 141, 120 },
        [11] = { 31.5, 53.5, 141, 120 },
        [12] = { 38.9, 29.3, 215, 120 },
        [13] = { 18.8, 84.2, 1537, 120 },
        [14] = { 20.4, 82.3, 1537, 120 },
        [15] = { 16.9, 80.7, 1537, 120 },
        [16] = { 21.9, 80.4, 1537, 120 },
        [17] = { 18.4, 78.7, 1537, 120 },
        [18] = { 20, 76.8, 1537, 120 },
        [19] = { 58.9, 13.7, 1537, 120 },
        [20] = { 58.9, 13.7, 1537, 900 },
        [21] = { 39.5, 12.4, 1537, 120 },
        [22] = { 39.5, 12.4, 1537, 900 },
        [23] = { 49.1, 95.4, 1637, 120 },
        [24] = { 52.5, 84.3, 1637, 120 },
        [25] = { 46.2, 65.6, 1637, 120 },
        [26] = { 47.3, 65.5, 1637, 120 },
        [27] = { 45.6, 64.2, 1637, 120 },
        [28] = { 46.1, 62.9, 1637, 120 },
        [29] = { 47, 62.7, 1637, 120 },
        [30] = { 17.8, 60.6, 1637, 120 },
        [31] = { 44.7, 61.5, 1638, 120 },
        [32] = { 66.1, 49, 1657, 120 },
        [33] = { 67.5, 49, 1657, 120 },
        [34] = { 69.1, 48.9, 1657, 120 },
        [35] = { 90.7, 35.8, 1657, 120 },
        [36] = { 86.5, 35.7, 1657, 120 },
        [37] = { 65.8, 31.8, 1657, 120 },
        [38] = { 67.2, 31.8, 1657, 120 },
        [39] = { 68.7, 31.7, 1657, 120 },
      },
    }
  pfDB["objects"]["data-turtle"][186250] = {
      ["coords"] = {
        [1] = { 30.4, 63, 141, 300 },
        [2] = { 30.3, 62.9, 141, 300 },
        [3] = { 63.4, 77.5, 1657, 300 },
        [4] = { 62.9, 77, 1657, 300 },
      },
    }
  pfDB["objects"]["data-turtle"][1000373] = {
      ["coords"] = {
        [1] = { 49.6, 73.5, 10, 25 },
        [2] = { 21.2, 69.6, 10, 25 },
        [3] = { 22.2, 69, 10, 25 },
        [4] = { 22, 67.8, 10, 25 },
        [5] = { 20.8, 67.4, 10, 25 },
        [6] = { 73, 53.8, 10, 25 },
        [7] = { 73.4, 53.2, 10, 25 },
        [8] = { 75.7, 42.3, 10, 25 },
        [9] = { 16.5, 71.2, 11, 25 },
        [10] = { 20.5, 69.1, 11, 25 },
        [11] = { 20, 69, 11, 25 },
        [12] = { 41.7, 88.1, 12, 25 },
        [13] = { 41.1, 87.3, 12, 25 },
        [14] = { 42.6, 86.8, 12, 25 },
        [15] = { 41.9, 86.8, 12, 25 },
        [16] = { 40.8, 86.7, 12, 25 },
        [17] = { 32.7, 86.4, 12, 25 },
        [18] = { 41.1, 86.2, 12, 25 },
        [19] = { 42.1, 86, 12, 25 },
        [20] = { 41.5, 85.9, 12, 25 },
        [21] = { 32, 85.4, 12, 25 },
        [22] = { 33.3, 85.4, 12, 25 },
        [23] = { 32.6, 84.4, 12, 25 },
        [24] = { 69.3, 80.2, 12, 25 },
        [25] = { 70.1, 79.3, 12, 25 },
        [26] = { 68.9, 78.9, 12, 25 },
        [27] = { 69.4, 78.2, 12, 25 },
        [28] = { 34.3, 57.8, 12, 25 },
        [29] = { 34.1, 51.4, 12, 25 },
        [30] = { 35, 51.2, 12, 25 },
        [31] = { 35.6, 50.5, 12, 25 },
        [32] = { 33.9, 50.5, 12, 25 },
        [33] = { 34.9, 50.5, 12, 25 },
        [34] = { 34.9, 50.2, 12, 25 },
        [35] = { 34.9, 49.9, 12, 25 },
        [36] = { 54.1, 49.7, 12, 25 },
        [37] = { 33.8, 49.5, 12, 25 },
        [38] = { 33.7, 48.3, 12, 25 },
        [39] = { 53.9, 47.8, 12, 25 },
        [40] = { 63, 95.7, 14, 25 },
        [41] = { 60.8, 90.2, 14, 25 },
        [42] = { 55.4, 34.5, 14, 25 },
        [43] = { 43.6, 30.1, 14, 25 },
        [44] = { 48.4, 15.7, 14, 25 },
        [45] = { 42.8, 15.1, 14, 25 },
        [46] = { 42.1, 8.9, 14, 25 },
        [47] = { 41.6, 42.6, 16, 300 },
        [48] = { 42.4, 93.2, 17, 300 },
        [49] = { 78.1, 47, 17, 25 },
        [50] = { 77, 44.2, 17, 25 },
        [51] = { 46.1, 38.1, 17, 25 },
        [52] = { 46.4, 38.1, 17, 25 },
        [53] = { 46.5, 37.9, 17, 25 },
        [54] = { 45.9, 37.5, 17, 25 },
        [55] = { 46.5, 37.4, 17, 25 },
        [56] = { 46.2, 37.1, 17, 25 },
        [57] = { 46, 37.1, 17, 25 },
        [58] = { 60.9, 24.7, 17, 300 },
        [59] = { 54, 20.7, 17, 25 },
        [60] = { 35, 87.8, 33, 25 },
        [61] = { 60.3, 87.6, 36, 25 },
        [62] = { 59.6, 86, 36, 25 },
        [63] = { 59.2, 85.6, 36, 25 },
        [64] = { 60, 85.5, 36, 25 },
        [65] = { 83.1, 80.4, 36, 25 },
        [66] = { 40.5, 19.3, 36, 25 },
        [67] = { 38.1, 13.6, 36, 25 },
        [68] = { 51.1, 23.5, 40, 25 },
        [69] = { 52, 22.8, 40, 25 },
        [70] = { 50.5, 21.8, 40, 25 },
        [71] = { 51.2, 20.5, 40, 25 },
        [72] = { 58.8, 18.2, 40, 25 },
        [73] = { 58, 18.2, 40, 25 },
        [74] = { 20.4, 46.2, 44, 25 },
        [75] = { 63.1, 58.6, 45, 25 },
        [76] = { 63.2, 58.2, 45, 25 },
        [77] = { 61.6, 57.7, 45, 25 },
        [78] = { 61, 57.6, 45, 25 },
        [79] = { 55.4, 40.3, 45, 25 },
        [80] = { 55, 39.6, 45, 25 },
        [81] = { 32.4, 29, 45, 25 },
        [82] = { 32.5, 28.3, 45, 25 },
        [83] = { 36, 52, 85, 25 },
        [84] = { 35.6, 52, 85, 25 },
        [85] = { 35.5, 51.7, 85, 25 },
        [86] = { 36.9, 51.6, 85, 25 },
        [87] = { 34.7, 51.6, 85, 25 },
        [88] = { 35.4, 51.3, 85, 25 },
        [89] = { 36.1, 51.3, 85, 25 },
        [90] = { 36.9, 50.7, 85, 25 },
        [91] = { 35.3, 50.4, 85, 25 },
        [92] = { 36.1, 50.4, 85, 25 },
        [93] = { 34.9, 50.3, 85, 25 },
        [94] = { 36.9, 50, 85, 25 },
        [95] = { 35.3, 49.6, 85, 25 },
        [96] = { 36.1, 49.6, 85, 25 },
        [97] = { 34.7, 49.4, 85, 25 },
        [98] = { 36.9, 49.4, 85, 25 },
        [99] = { 23.3, 61.3, 141, 25 },
        [100] = { 27.3, 61.1, 141, 25 },
        [101] = { 31.2, 56.4, 141, 25 },
        [102] = { 23.5, 48.2, 141, 25 },
        [103] = { 43.6, 76.3, 148, 25 },
        [104] = { 68.3, 19.1, 148, 300 },
        [105] = { 44.7, 59.4, 215, 25 },
        [106] = { 44.2, 59.4, 215, 25 },
        [107] = { 45, 58.7, 215, 25 },
        [108] = { 44.3, 58.7, 215, 25 },
        [109] = { 44.1, 58.3, 215, 25 },
        [110] = { 44.6, 58.1, 215, 25 },
        [111] = { 51.1, 38.5, 215, 25 },
        [112] = { 47.6, 29.9, 215, 25 },
        [113] = { 51.2, 28.4, 215, 25 },
        [114] = { 39.9, 25.2, 215, 25 },
        [115] = { 45.7, 22.6, 215, 25 },
        [116] = { 45.6, 21.4, 215, 25 },
        [117] = { 47, 16, 215, 25 },
        [118] = { 64.1, 62.4, 267, 25 },
        [119] = { 64.7, 62.2, 267, 25 },
        [120] = { 63.8, 61.9, 267, 25 },
        [121] = { 65.3, 60.8, 267, 25 },
        [122] = { 64.3, 60.4, 267, 25 },
        [123] = { 53.9, 56.5, 267, 25 },
        [124] = { 53.9, 56, 267, 25 },
        [125] = { 34.5, 46.9, 267, 25 },
        [126] = { 35, 46.9, 267, 25 },
        [127] = { 34.1, 46.8, 267, 25 },
        [128] = { 35.5, 46.7, 267, 25 },
        [129] = { 34.3, 46.2, 267, 25 },
        [130] = { 35.9, 46, 267, 25 },
        [131] = { 35.7, 45.6, 267, 25 },
        [132] = { 34.7, 45.3, 267, 25 },
        [133] = { 35.2, 45, 267, 25 },
        [134] = { 34.2, 41.3, 267, 25 },
        [135] = { 34.9, 41.1, 267, 25 },
        [136] = { 35.6, 41.1, 267, 25 },
        [137] = { 35.7, 40.6, 267, 25 },
        [138] = { 34.2, 40.4, 267, 25 },
        [139] = { 34.9, 40.3, 267, 25 },
        [140] = { 31.6, 38.5, 267, 25 },
        [141] = { 31.3, 38.3, 267, 25 },
        [142] = { 30.6, 38.1, 267, 25 },
        [143] = { 31.2, 37.2, 267, 25 },
        [144] = { 31.6, 37.1, 267, 25 },
        [145] = { 30.5, 36.8, 267, 25 },
        [146] = { 33.8, 35.5, 267, 25 },
        [147] = { 61.6, 25.1, 267, 25 },
        [148] = { 61, 23.7, 267, 25 },
        [149] = { 60.6, 23.3, 267, 25 },
        [150] = { 61.4, 23.2, 267, 25 },
        [151] = { 81.5, 18.8, 267, 25 },
        [152] = { 22.4, 52.5, 331, 25 },
        [153] = { 51.5, 60.6, 357, 300 },
        [154] = { 51.5, 60.4, 357, 300 },
        [155] = { 51.5, 59.9, 357, 300 },
        [156] = { 51.6, 59.6, 357, 300 },
        [157] = { 51.5, 59.3, 357, 300 },
        [158] = { 49.1, 19.3, 357, 25 },
        [159] = { 43.6, 17.6, 357, 25 },
        [160] = { 43.7, 16.5, 357, 25 },
        [161] = { 44.1, 16.4, 357, 25 },
        [162] = { 43.5, 16.3, 357, 25 },
        [163] = { 43.7, 16, 357, 25 },
        [164] = { 28.2, 24.4, 400, 300 },
        [165] = { 31.1, 36.7, 440, 300 },
        [166] = { 78.4, 64.7, 490, 300 },
        [167] = { 38.3, 12.6, 490, 300 },
        [168] = { 37.2, 11.5, 490, 300 },
        [169] = { 35.8, 41.3, 493, 25 },
        [170] = { 54.5, 49, 1497, 25 },
        [171] = { 69.3, 71.3, 1519, 25 },
        [172] = { 37, 67, 1519, 25 },
        [173] = { 33.8, 64.6, 1519, 25 },
        [174] = { 35.7, 62.9, 1519, 25 },
        [175] = { 55.1, 59.3, 1537, 25 },
        [176] = { 36.3, 83.3, 1637, 25 },
        [177] = { 49.8, 41.2, 1638, 25 },
        [178] = { 78.4, 28.5, 1638, 25 },
        [179] = { 77.7, 22.4, 1638, 25 },
        [180] = { 29.4, 69, 1657, 25 },
        [181] = { 48.7, 68.3, 1657, 25 },
        [182] = { 67.3, 45.4, 1657, 25 },
        [183] = { 30.1, 6.3, 1657, 25 },
        [184] = { 36.2, 93.5, 3478, 25 },
        [185] = { 35.3, 92.9, 3478, 25 },
        [186] = { 36.6, 92.6, 3478, 25 },
        [187] = { 36.4, 92.5, 3478, 25 },
        [188] = { 35.9, 91.5, 3478, 25 },
        [189] = { 36.4, 91.2, 3478, 25 },
        [190] = { 89.7, 9.9, 5179, 25 },
        [191] = { 90.2, 9.9, 5179, 25 },
        [192] = { 89.4, 9.8, 5179, 25 },
        [193] = { 90.6, 9.7, 5179, 25 },
        [194] = { 89.5, 9.2, 5179, 25 },
        [195] = { 91, 9.1, 5179, 25 },
        [196] = { 90.8, 8.7, 5179, 25 },
        [197] = { 89.9, 8.5, 5179, 25 },
        [198] = { 90.4, 8.2, 5179, 25 },
        [199] = { 89.5, 5, 5179, 25 },
        [200] = { 90.1, 4.9, 5179, 25 },
        [201] = { 90.7, 4.8, 5179, 25 },
        [202] = { 90.8, 4.4, 5179, 25 },
        [203] = { 89.5, 4.2, 5179, 25 },
        [204] = { 90.1, 4.1, 5179, 25 },
        [205] = { 87.2, 2.6, 5179, 25 },
        [206] = { 86.9, 2.4, 5179, 25 },
        [207] = { 86.3, 2.2, 5179, 25 },
        [208] = { 86.9, 1.4, 5179, 25 },
        [209] = { 87.2, 1.3, 5179, 25 },
        [210] = { 86.3, 1.1, 5179, 25 },
      },
    }

  -- items: 3 absent from the turtle build, 7 only a placeholder there
  pfDB["items"]["data-turtle"][3053] = {
      ["U"] = {
        [2344] = 1.5,
        [62114] = 1.5,
        [62115] = 1.5,
        [62117] = 1.5,
        [62131] = 1.5,
        [62132] = 1.5,
        [62133] = 1.5,
        [62134] = 1.5,
      },
    }
  pfDB["items"]["data-turtle"][9425] = {
      ["U"] = {
        [4848] = 0.02,
        [4853] = 0.06,
        [4855] = 0.02,
        [4860] = 0.02,
        [7012] = 0.02,
        [7023] = 0.02,
        [7320] = 0.02,
        [7321] = 0.02,
        [61364] = 0.02,
        [61365] = 0.02,
        [61388] = 0.02,
        [61389] = 0.02,
        [61390] = 0.02,
        [61391] = 0.02,
        [61417] = 0.02,
      },
    }
  pfDB["items"]["data-turtle"][50234] = {
      ["V"] = {
        [50070] = 0,
      },
    }
  pfDB["items"]["data-turtle"][50235] = {
      ["V"] = {
        [50070] = 0,
      },
    }
  pfDB["items"]["data-turtle"][50238] = {
      ["V"] = {
        [51531] = 0,
        [51533] = 0,
      },
    }
  pfDB["items"]["data-turtle"][60002] = {
      ["V"] = {
        [50070] = 0,
      },
    }
  pfDB["items"]["data-turtle"][65029] = {
      ["V"] = {
        [50070] = 0,
      },
    }
  pfDB["items"]["data-turtle"][65031] = {
      ["V"] = {
        [50070] = 0,
      },
    }
  pfDB["items"]["data-turtle"][81187] = {
      ["V"] = {
        [50070] = 0,
        [51531] = 0,
        [51533] = 0,
        [61644] = 0,
        [81057] = 0,
      },
    }
  pfDB["items"]["data-turtle"][81278] = {
      ["V"] = {
        [81063] = 0,
      },
    }

  -- minimap: 1 absent from the turtle build, 0 only a placeholder there
  -- minimap and meta are top-level pfDB keys, not nested under a
  -- "data-turtle" field like the other databases -- see
  -- db/minimap-turtle.lua and the separate handling at the bottom of
  -- patchtable.lua. Using the nested path here made this line throw,
  -- which aborted the rest of the file and silently dropped 166 of the
  -- corrections below it.
  pfDB["minimap-turtle"][2041] = { 1513.0, 1003.0 }

  -- quests-itemreq: 1 absent from the turtle build, 0 only a placeholder there
  pfDB["quests-itemreq"]["data-turtle"][15209] = {
      [-177528] = "18987",
      [-944] = "18987",
    }
end

-- ==== corrections carried over from pfQuest-octo ====

do -- area trigger
  -- Investigating Hateforge (Quest)
  pfDB["areatrigger"]["data-turtle"][40486] = { ["coords"] = { [1] = { 96.1, 57.6, 46 } } }

  -- Gathering Intel (Quest)
  pfDB["areatrigger"]["data-turtle"][80204] = { ["coords"] = { [1] = { 78.3, 72.3, 38 } } }
end

do -- items
  -- Once Upon a Sheep: Lost Farm Sheep (Interaction)
  pfDB["items"]["data-turtle"][51220] = { ["U"] = { [50610] = 100 } }

  -- The Boran Family: Letter from Karl & Letter from Samual (Interaction)
  pfDB["items"]["data-turtle"][60202] = { ["U"] = { [1242] = 100 } }
  pfDB["items"]["data-turtle"][60203] = { ["U"] = { [92936] = 100 } }

  -- Sailors Innovation: Pinch of Salt (Interaction)
  pfDB["items"]["data-turtle"][60207] = { ["U"] = { [91950] = 100 } }

  -- Southsea Reserve: Southsea Reserve (Interaction)
  pfDB["items"]["data-turtle"][60217] = { ["U"] = { [92137] = 100 } }

  -- The Good Snuff: 'The Good Snuff' (Interaction)
  pfDB["items"]["data-turtle"][60597] = { ["U"] = { [8139] = 100 } }

  -- Reports of Dustwallow: Sentry Point Report & North Point Report (Interaction)
  pfDB["items"]["data-turtle"][60602] = { ["U"] = { [60729] = 100 } }
  pfDB["items"]["data-turtle"][60603] = { ["U"] = { [60730] = 100 } }

  -- Report from Burnside: Report from Burnside (Interaction)
  pfDB["items"]["data-turtle"][60635] = { ["U"] = { [60792] = 100 } }

  -- Fel Energy Irregularities I: Engineer Wigglestip's Report (Interaction)
  pfDB["items"]["data-turtle"][60640] = { ["U"] = { [60794] = 100 } }

  -- To Purchase Secret Information: Arcane Golem Core Information (Interaction)
  pfDB["items"]["data-turtle"][60670] = { ["U"] = { [8139] = 100 } }

  -- Preparation for Divination: Arcane Resonator (Interaction)
  pfDB["items"]["data-turtle"][60815] = { ["U"] = { [2543] = 100 } }

  -- Apple a Day: Healing Balm (Interaction)
  pfDB["items"]["data-turtle"][80865] = { ["U"] = { [8090] = 100 } }
end

do -- units/npcs
  -- AQ Commendation NPCs
  pfDB["units"]["data-turtle"][15761] = { }
  pfDB["units"]["data-turtle"][15762] = { }
  pfDB["units"]["data-turtle"][15763] = { }
  pfDB["units"]["data-turtle"][15764] = { }
  pfDB["units"]["data-turtle"][15765] = { }
  pfDB["units"]["data-turtle"][15766] = { }
  pfDB["units"]["data-turtle"][15767] = { }
  pfDB["units"]["data-turtle"][15768] = { }

  -- Fara Boltbreaker: Horde only
  pfDB["units"]["data-turtle"][50530]["fac"] = "H"

  -- quest_40124_dummy_triger
  pfDB["units"]["enUS-turtle"][60312] = "Spitelash Shrine"
  pfDB["units"]["data-turtle"][60312]["coords"] = { [1] = { 48.8, 55.2, 16, 333 } }

  -- Kex Blowmaster: Horde only
  pfDB["units"]["data-turtle"][60443]["fac"] = "H"

  -- Technician Steelbolt: Horde only
  pfDB["units"]["data-turtle"][60960]["fac"] = "H"

  -- Head Technician Klazfit: Horde only
  pfDB["units"]["data-turtle"][60961]["fac"] = "H"

  -- Fusemaster Blammo: Horde only
  pfDB["units"]["data-turtle"][60962]["fac"] = "H"

  -- Gig Xevno: Horde only
  pfDB["units"]["data-turtle"][60967]["fac"] = "H"

  -- Security Officer Mort Tozzlefume: Horde only
  pfDB["units"]["data-turtle"][60970]["fac"] = "H"

  -- Senior Foreman Nazz Firecracker: Horde only
  pfDB["units"]["data-turtle"][61024]["fac"] = "H"

  -- Alleana Moonfeather (Ashenvale), coords missing
  pfDB["units"]["data-turtle"][61292]["coords"] = { [1] = { 85, 43.5, 331, 280 } }

  -- Pezzik Villamar: Horde only
  pfDB["units"]["data-turtle"][70060]["fac"] = "H"

    -- Nert Blastentom (Razor Hill): Horde only
  pfDB["units"]["data-turtle"][80121]["fac"] = "H"

  -- Grand Taskmaster Nert Blastentom (Sparkwater Port): Horde only
  pfDB["units"]["data-turtle"][80178]["fac"] = "H"

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80270] = "Search Mage Tower"
  pfDB["units"]["data-turtle"][80270]["coords"] = { [1] = { 48.7, 87.4, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80271] = "Search Mage District"
  pfDB["units"]["data-turtle"][80271]["coords"] = { [1] = { 50.4, 86.5, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80272] = "Search Mage District Tavern"
  pfDB["units"]["data-turtle"][80272]["coords"] = { [1] = { 41.7, 82.6, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80273] = "Search Mage District Tavern Basement"
  pfDB["units"]["data-turtle"][80273]["coords"] = { [1] = { 39.5, 84.8, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80274] = "Search Stormwind Park"
  pfDB["units"]["data-turtle"][80274]["coords"] = { [1] = { 36.5, 67.4, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80275] = "Search Dwarven District"
  pfDB["units"]["data-turtle"][80275]["coords"] = { [1] = { 64.6, 38.3, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80276] = "Search Dwarf District Embassy"
  pfDB["units"]["data-turtle"][80276]["coords"] = { [1] = { 65.4, 29.6, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80277] = "Search Little Silvermoon"
  pfDB["units"]["data-turtle"][80277]["coords"] = { [1] = { 64.1, 46.8, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80278] = "Search Deeprun Tram Entrance"
  pfDB["units"]["data-turtle"][80278]["coords"] = { [1] = { 66.3, 34.3, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80279] = "Search Stormwind Keep"
  pfDB["units"]["data-turtle"][80279]["coords"] = { [1] = { 74.3, 46.3, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80280] = "Search Old Town"
  pfDB["units"]["data-turtle"][80280]["coords"] = { [1] = { 75.6, 61.9, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80281] = "Search Old Town Tavern"
  pfDB["units"]["data-turtle"][80281]["coords"] = { [1] = { 76.1, 54.2, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80282] = "Search Old Town Barracks"
  pfDB["units"]["data-turtle"][80282]["coords"] = { [1] = { 77.6, 66.2, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80283] = "Search Cathedral Square"
  pfDB["units"]["data-turtle"][80283]["coords"] = { [1] = { 55.5, 56.6, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80284] = "Search Orphanage"
  pfDB["units"]["data-turtle"][80284]["coords"] = { [1] = { 56.4, 53.2, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80285] = "Search Cathedral"
  pfDB["units"]["data-turtle"][80285]["coords"] = { [1] = { 51.1, 47.7, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80286] = "Search Cathedral Basement"
  pfDB["units"]["data-turtle"][80286]["coords"] = { [1] = { 52.5, 43.5, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80287] = "Search Cathedral Catacombs"
  pfDB["units"]["data-turtle"][80287]["coords"] = { [1] = { 52.9, 44.8, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80288] = "Search Trade District"
  pfDB["units"]["data-turtle"][80288]["coords"] = { [1] = { 62.5, 72.8, 1519, 30 } }

  -- Quest 80261 Custom Objective
  pfDB["units"]["enUS-turtle"][80289] = "Search Stormwind Visitor Center"
  pfDB["units"]["data-turtle"][80289]["coords"] = { [1] = { 64, 77.3, 1519, 30 } }

  -- Volz'draza: Horde only
  pfDB["units"]["data-turtle"][80799]["fac"] = "H"

  -- Miley Wildbit: Horde only
  pfDB["units"]["data-turtle"][80902]["fac"] = "H"

  -- Drazzit Dripvalve: Horde only
  pfDB["units"]["data-turtle"][80932]["fac"] = "H"

  -- Vanessa Clang: Horde only
  pfDB["units"]["data-turtle"][80961]["fac"] = "H"

  -- Moxie Steelgrille: Horde only
  pfDB["units"]["data-turtle"][81250]["fac"] = "H"

  -- Vixie Dampknob: Horde only
  pfDB["units"]["data-turtle"][81258]["fac"] = "H"

  -- Qik Peddlechin: Horde only
  pfDB["units"]["data-turtle"][81259]["fac"] = "H"

  -- Wrix Ozzlenut: Horde only
  pfDB["units"]["data-turtle"][91200]["fac"] = "H"

  -- Oilworker Razlik: Horde only
  pfDB["units"]["data-turtle"][91208]["fac"] = "H"

  -- Oil Manager Tizzleflux: Horde only
  pfDB["units"]["data-turtle"][91213]["fac"] = "H"

  -- Technician Spuzzle: Horde only
  pfDB["units"]["data-turtle"][91214]["fac"] = "H"

  -- Krez the Wise: Horde only
  pfDB["units"]["data-turtle"][91232]["fac"] = "H"

  -- Technician Grimzlow: Horde only
  pfDB["units"]["data-turtle"][91234]["fac"] = "H"

  -- Tradesman Laz: Horde only
  pfDB["units"]["data-turtle"][91237]["fac"] = "H"

  -- Pazzle Brightwrench: Horde only
  pfDB["units"]["data-turtle"][91259]["fac"] = "H"

  -- Shak 'The Hack': Horde only
  pfDB["units"]["data-turtle"][91260]["fac"] = "H"

  -- Big Fraggle: Horde only
  pfDB["units"]["data-turtle"][91274]["fac"] = "H"

  -- Tarlo Farcrack: Horde only
  pfDB["units"]["data-turtle"][91292]["fac"] = "H"

  -- Watch Sergeant Arthur: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92012]["coords"] = { [1] = { 1.9, 52.8, 8, 25 } }

  -- Watchman Damion: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92014]["coords"] = { [1] = { 1.6, 50.8, 8, 25 } }

  -- Watch Paladin Janathos: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92017]["coords"] = { [1] = { 2.4, 50.6, 8, 25 } }

  -- Sir Areyntall: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92018]["coords"] = { [1] = { 1.6, 50.3, 8, 25 } }

  -- Janet Hollowworth: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92019]["coords"] = { [1] = { 0.9, 49.4, 8, 25 } }

  -- Howard Gray: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92020]["coords"] = { [1] = { 1.5, 50, 8, 25 } }

  -- Lucas: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92021]["coords"] = { [1] = { 2, 52, 8, 25 } }

  -- 'Sly' Duncan: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92022]["coords"] = { [1] = { 3.7, 49.7, 8, 25 } }

  -- Quartermaster Davin: Moved from Deadwind Pass -> Swamp of Sorrows
  pfDB["units"]["data-turtle"][92023]["coords"] = { [1] = { 3.5, 50.6, 8, 25 } }

  -- Flaz Fusemix: Horde only
  pfDB["units"]["data-turtle"][92187]["fac"] = "H"

  -- Yeggle Powderscrew: Horde only
  pfDB["units"]["data-turtle"][92188]["fac"] = "H"

  -- Blazno Blastpipe: Horde only
  pfDB["units"]["data-turtle"][92192]["fac"] = "H"

  -- Joachim Brenlow (Stormwind)
  pfDB["units"]["data-turtle"][1311] = {
    ["coords"] = {
      [1] = { 51.4, 94.1, 1519, 310 },
    },
    ["fac"] = "A",
    ["lvl"] = "30",
  }

  -- Angus Stern (Stormwind)
  pfDB["units"]["data-turtle"][1141] = {
    ["coords"] = {
      [1] = { 51.8, 93.6, 1519, 30 },
    },
    ["fac"] = "A",
    ["lvl"] = "60",
  }

  -- Highlord Bolvar Fordragon (Stormwind)
  pfDB["units"]["data-turtle"][1748] = {
    ["coords"] = {
      [1] = { 80.2, 38.3, 1519, 30 },
    },
    ["fac"] = "A",
    ["lvl"] = "63",
  }

  -- Lady Katrana Prestor (Stormwind)
  pfDB["units"]["data-turtle"][1749] = {
    ["coords"] = {
      [1] = { 80.1, 38.2, 1519, 30 },
    },
    ["fac"] = "A",
    ["lvl"] = "62",
  }

  --  Duthorian Rall (Stormwind)
  pfDB["units"]["data-turtle"][6171]["coords"] = { [1] = { 50.5, 47.5, 1519, 30 } }

  -- Barltok Kettleburn (Dun Agrath)
  pfDB["units"]["data-turtle"][52068]["coords"] = { [1] = { 21, 71.4, 11, 120 } }
end

do -- quests
  -- Great Bear Spirit: Great Bear Spirit
  pfDB["quests"]["data-turtle"][5929]["obj"] = { ["U"] = { 11956 } }
  pfDB["quests"]["data-turtle"][5930]["obj"] = { ["U"] = { 11956 } }

  -- Horde Defender's Axe: Stolen Weapon Plans
  pfDB["quests"]["data-turtle"][39995]["obj"]["O"] = { 300531 }

  -- Horde Defender's Axe: Human Tombstone
  pfDB["quests"]["data-turtle"][39998]["obj"]["O"] = { 300532 }

  -- Interfering Naga: quest_40124_dummy_triger (Spitelash Shrine)
  pfDB["quests"]["data-turtle"][40124]["obj"]["U"] = { 6195, 60312 }

  -- The Way-Stones of Old: Way-Stone of Eldarath
  pfDB["quests"]["data-turtle"][40252]["end"] = { ["O"] = { 2010849 } }

  -- Restoring the Ley Lines: Way-Stone of Eldarath
  pfDB["quests"]["data-turtle"][40253]["end"] = { ["O"] = { 2010849 } }

  -- Restoring the Ley Lines: Ashan Stone
  pfDB["quests"]["data-turtle"][40253]["obj"] = { ["O"] = { 2010851 } }

  -- Keeping Secrets: Way-Stone of Eldarath
  pfDB["quests"]["data-turtle"][40254]["start"] = { ["O"] = { 2010849 } }
  pfDB["quests"]["data-turtle"][40254]["end"] = { ["O"] = { 2010849 } }

  -- Breaking the Felstar: Corrupted Felstone
  pfDB["quests"]["data-turtle"][40377]["obj"]["O"] = { 2010883 }

  -- Sacred Waters of Eldre'thalas: Bowl of Sacred Water
  pfDB["quests"]["data-turtle"][40382]["obj"] = { ["O"] = { 2010815 } }

  -- Investigating Hateforge: Fake Area Trigger
  pfDB["quests"]["data-turtle"][40486]["obj"] = { ["A"] = { 40486 } }

  -- Family Above All: Abandoned Murloc Hut & Abandoned Murloc Nest
  pfDB["quests"]["data-turtle"][40541]["obj"] = { ["O"] = { 2010918, 2010919 } }

  -- The Shield's Owner: Private Talmand, Private Sleightor, Private Valnor (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40554]["obj"] = { ["U"] = { 60949, 60950, 60951 } }

  -- Sleepwalking at Day: Bert Mano (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40567]["obj"] = { ["U"] = { 52017 } }

  -- The Redbrand Archive: The Redbrand Archive
  pfDB["quests"]["data-turtle"][40605]["obj"] = { ["O"] = { 2010929 } }

  -- Controlling Sailors: Sailor Hylreth, Sailor Brewen, Sailor Pardol (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40660]["obj"] = { ["U"] = { 61013, 61015, 61016 } }

  -- A Journey for Vengeance: Grumnir Battlebeard (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40691]["obj"] = { ["U"] = { 60993 } }

  -- Conflicting Questions: Faldan Moonshatter (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40698]["obj"] = { ["U"] = { 60471 } }

  -- The Land of Kings: Gong of Corthan
  pfDB["quests"]["data-turtle"][40713]["obj"] = { ["O"] = { 2010946 } }

  -- The Missing Friend!: Nibu (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40771]["obj"] = { ["U"] = { 61157 } }

  -- Words of Wisdom: Teloren, Baritanas Skyriver, Daelyshia, Vesprystus (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40799]["obj"] = { ["U"] = { 4407, 6706, 4267, 3838 } }

  -- The Family Name: Sharptalon (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40800]["obj"] = { ["U"] = { 12676 } }

  -- Patience is the Key: Brolthan Ironglade (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40801]["obj"] = { ["U"] = { 61147 } }

  -- Pressure is the Key: Commander Starwind (Interaction with no item given)
  pfDB["quests"]["data-turtle"][40807]["obj"] = { ["U"] = { 61143 } }

  -- WANTED: Shazknock!: end unit is Horde only
  pfDB["quests"]["data-turtle"][55049]["race"] = 434

  -- Lucky Coin: Use Teresa's Copper Coin (51425) at this object location
  pfDB["quests"]["data-turtle"][60050]["obj"] = { ["O"] = { 1000220 } }

  -- Gathering Intel: Fake Area Trigger
  pfDB["quests"]["data-turtle"][80204]["obj"] = { ["A"] = { 80204 } }

  -- Slaking Their Thirst: Well
  pfDB["quests"]["data-turtle"][80205]["obj"] = { ["O"] = { 3000202 } }

  -- Dark Iron Scrapping: Shadowforge Cage
  pfDB["quests"]["data-turtle"][80207]["obj"]["O"] = { 3000203 }

  -- Sunblade Reunion: Malvinah Sunblade (Interaction with no item given)
  pfDB["quests"]["data-turtle"][80208]["obj"] = { ["U"] = { 80200 } }

  -- Porting to Goldshire: Magistrix Ishalah (Interaction with no item given)
  pfDB["quests"]["data-turtle"][80209]["obj"]["U"] = { 80213 }

  -- Porting to Goldshire: Portal to Goldshire
  pfDB["quests"]["data-turtle"][80209]["obj"]["O"] = { 3000204 }

  -- Assisting the Children of the Sun: Caledra Dawnbreeze (Interaction with no item given)
  pfDB["quests"]["data-turtle"][80250]["obj"] = { ["U"] = { 1752 } }

  -- Teslinah's Search I: Stand at these units
  pfDB["quests"]["data-turtle"][80261]["obj"] = { ["U"] = { 80270, 80271, 80272, 80273 } }

  -- Teslinah's Search II: Stand at these units
  pfDB["quests"]["data-turtle"][80262]["obj"] = { ["U"] = { 80274, 80275, 80276, 80277 } }

  -- Teslinah's Search III: Stand at these units
  pfDB["quests"]["data-turtle"][80263]["obj"] = { ["U"] = { 80278, 80279, 80280, 80281 } }

  -- Teslinah's Search IV: Stand at these units
  pfDB["quests"]["data-turtle"][80264]["obj"] = { ["U"] = { 80282, 80283, 80284, 80285 } }

  -- Teslinah's Search V: Stand at these units
  pfDB["quests"]["data-turtle"][80265]["obj"] = { ["U"] = { 80286, 80287, 80288, 80289 } }

  -- The Lost Tablets: Ancient Thalassian Tablet
  pfDB["quests"]["data-turtle"][80290]["obj"] = { ["O"] = { 181583 } }

  -- The Shadow Well: Thalo's Skeleton
  pfDB["quests"]["data-turtle"][80291]["obj"] = { ["O"] = { 181584 } }

  -- VIP Invites: Interactions with no item given
  pfDB["quests"]["data-turtle"][80392]["obj"] = { ["U"] = { 3391, 2496 } }

  -- A Glittering Opportunity: Mysterious Glittering Object (The Barrens)
  pfDB["quests"]["data-turtle"][80395]["obj"] = { ["O"] = { 3000284 } }
  pfDB["quests"]["data-turtle"][80395]["end"] = { ["O"] = { 3000284 } }

  -- A Bloody Good Deed: Mysterious Glittering Object (The Barrens)
  pfDB["quests"]["data-turtle"][80396]["start"] = { ["O"] = { 3000284 } }
  pfDB["quests"]["data-turtle"][80396]["end"] = { ["O"] = { 3000284 } }

  -- A Letter From a Friend: Mysterious Glittering Object (Tanaris)
  pfDB["quests"]["data-turtle"][80407]["end"] = { ["O"] = { 3000246 } }

  -- A Slaughter for Brains: Mysterious Glittering Object (Tanaris)
  pfDB["quests"]["data-turtle"][80408]["start"] = { ["O"] = { 3000246 } }

  -- Return to Kheyna: Mysterious Glittering Object (Tanaris)
  pfDB["quests"]["data-turtle"][80409]["end"] = { ["O"] = { 3000246 } }
end

-- ==== corrections from the TurtleWoW pack ====

do -- zones
  -- Several zone IDs share a name with a functional zone but have no NPC or
  -- object coordinate references, making them phantoms. GetMapIDByName scans
  -- the locale table with pairs() (non-deterministic order), so it may return
  -- a phantom ID instead of the functional one, causing quests and minimap
  -- nodes to not appear inside those dungeons.
  --
  -- TurtleWoW-specific phantom -> Functional mappings:
  --   5600 "Dragonmaw Retreat"  -> 5601 (has minimap + units)
  --   5098 "Hateforge Quarry"   -> 5103 (has minimap + units)
  --   5550 "Ruins of Grim Batol"-> 5639 (has units)
  --
  -- Vanilla dungeon zone IDs that still hold all NPC/object data (verified
  -- via coordinate references in units-turtle.lua and objects-turtle.lua):
  --   209  "Shadowfang Keep"  (181 NPC refs, 35 object refs)
  --   1581 "The Deadmines"
  --   1583 "Blackrock Spire"
  --   1584 "Blackrock Depths" (1085 NPC refs, 462 object refs)
  -- The 5000+ IDs below share those names but have zero NPC/object refs.
  -- They are removed so GetMapIDByName resolves to the IDs with real content.
  --
  -- Vanilla ID -> Phantom replacement(s):
  --    209 "Shadowfang Keep"  -> 5132, 5150, 5161, 5169, 5173, 5177
  --   1581 "The Deadmines"   -> 5138
  --   1583 "Blackrock Spire" -> 5139, 5155, 5164, 5170, 5178
  --   1584 "Blackrock Depths"-> 5140
  local phantom_zones = {
    5600, 5098, 5550,
    5132, 5138, 5139, 5140, 5150, 5161,
    5155, 5164, 5169, 5170, 5173, 5177, 5178,
  }
  local zone_locales = { "enUS", "deDE", "esES", "ptBR", "zhCN" }
  for _, locale in pairs(zone_locales) do
    local tbl = pfDB["zones"][locale .. "-turtle"]
    if tbl then
      for _, zid in pairs(phantom_zones) do
        tbl[zid] = nil
      end
    end
  end
end

do -- area trigger
end

do -- items
end

do -- quests
  -- Add "Dark Iron Gunpowder Keg" to objectives of "Vile Dwarven Pigs"
  -- The extractor scripts did not catch those, as the objetive is filled via a Gossip on use.
  pfDB["quests"]["data-turtle"][41682]["obj"]["O"] = { 2020173 }

  -- Add "Head of Geshgan" to the loot table of "Geshgan"
  -- This can be removed by the next database export
  pfDB["items"]["data-turtle"][41783]["U"] = { [62217] = 1.0 }
end
